"use client";

import { Document, Page, Text, View } from "@react-pdf/renderer";
import {
  CONTRACT_DISCLAIMER_EN,
  contractClauses,
  type ContractVars,
} from "@/lib/docs/contract";
import { pdfStyles as s } from "./styles";

/**
 * 英文輸出契約書ひな形PDF。
 * 官庁確認ゲート未完了の間はDRAFT透かし＋未確認事項リストを刷り込む
 * （書類自体に警告を背負わせる。締結そのものは層3・アプリ範囲外）。
 */
export default function ContractPdf({
  vars,
  isDraft,
  outstanding,
}: {
  vars: ContractVars;
  isDraft: boolean;
  outstanding: string[];
}) {
  const renderValue = (key: keyof ContractVars, i: number) => {
    const value = vars[key];
    return value ? (
      <Text key={i} style={s.value}>
        {value}
      </Text>
    ) : (
      <Text key={i} style={s.missing}>
        ____________
      </Text>
    );
  };

  return (
    <Document title="Sales Agreement (Template)">
      <Page size="A4" style={s.page}>
        {isDraft && <Text style={s.watermark} fixed>DRAFT</Text>}

        <Text style={s.title}>SALES AGREEMENT</Text>

        {contractClauses().map((clause) => (
          <View key={clause.title} style={s.block}>
            <Text style={s.clauseTitle}>{clause.title}</Text>
            <Text>
              {clause.segments.map((seg, i) =>
                typeof seg === "string" ? (
                  <Text key={i}>{seg}</Text>
                ) : (
                  renderValue(seg.var, i)
                ),
              )}
            </Text>
          </View>
        ))}

        {isDraft && (
          <View style={s.outstandingBox}>
            <Text style={s.outstandingTitle}>
              DRAFT — OUTSTANDING CONFIRMATIONS BEFORE SIGNING
            </Text>
            {outstanding.map((o, i) => (
              <Text key={i} style={{ fontSize: 9 }}>
                • {o}
              </Text>
            ))}
          </View>
        )}

        <View style={s.signRow}>
          <View style={s.signBox}>
            <View style={s.signLine} />
            <Text style={{ fontSize: 8 }}>The Seller (signature / date)</Text>
          </View>
          <View style={s.signBox}>
            <View style={s.signLine} />
            <Text style={{ fontSize: 8 }}>The Buyer (signature / date)</Text>
          </View>
        </View>

        <Text style={s.footer} fixed>
          {CONTRACT_DISCLAIMER_EN}
          {"\n"}Generated by Toika Export Navigator (demo)
        </Text>
      </Page>
    </Document>
  );
}
