"use client";

import { Document, Page, Text, View } from "@react-pdf/renderer";
import { computeAmount, type InvoiceVars } from "@/lib/docs/invoice";
import { pdfStyles as s } from "./styles";

function Field({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ marginBottom: 6 }}>
      <Text style={s.label}>{label}</Text>
      <Text>{value || "-"}</Text>
    </View>
  );
}

/** コマーシャルインボイスPDF（フォーム入力→出力） */
export default function InvoicePdf({ vars }: { vars: InvoiceVars }) {
  const amount = computeAmount(vars.quantity, vars.unitPrice);
  return (
    <Document title="Commercial Invoice">
      <Page size="A4" style={s.page}>
        <Text style={s.title}>COMMERCIAL INVOICE</Text>

        <View style={s.row}>
          <View style={{ width: "55%", paddingRight: 12 }}>
            <Field label="Exporter / Shipper" value={`${vars.exporterName}\n${vars.exporterAddress}`} />
            <Field label="Consignee" value={`${vars.consigneeName}\n${vars.consigneeAddress}`} />
          </View>
          <View style={{ width: "45%" }}>
            <Field label="Invoice No." value={vars.invoiceNo} />
            <Field label="Date" value={vars.invoiceDate} />
            <Field label="Incoterms" value={vars.incoterms} />
            <Field label="Vessel" value={vars.vessel} />
          </View>
        </View>

        <View style={s.row}>
          <View style={{ width: "50%" }}>
            <Field label="Port of Loading" value={vars.portLoading} />
          </View>
          <View style={{ width: "50%" }}>
            <Field label="Port of Discharge" value={vars.portDischarge} />
          </View>
        </View>

        <View style={s.tableHeader}>
          <Text style={{ width: "46%" }}>Description of Goods</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>Quantity (CTNS)</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>Unit Price ({vars.currency || "-"})</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>Amount ({vars.currency || "-"})</Text>
        </View>
        <View style={s.tableRow}>
          <Text style={{ width: "46%" }}>{vars.itemDesc || "-"}</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>{vars.quantity || "-"}</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>{vars.unitPrice || "-"}</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>{amount || "-"}</Text>
        </View>
        <View style={[s.row, { marginTop: 8, justifyContent: "flex-end" }]}>
          <Text style={{ fontFamily: "Helvetica-Bold" }}>
            TOTAL: {vars.currency || ""} {amount || "-"}
          </Text>
        </View>

        <View style={{ marginTop: 24 }}>
          <Text style={s.label}>Country of Origin</Text>
          <Text>JAPAN</Text>
        </View>

        <View style={[s.signRow, { justifyContent: "flex-end" }]}>
          <View style={s.signBox}>
            <View style={s.signLine} />
            <Text style={{ fontSize: 8 }}>Signature of Exporter</Text>
          </View>
        </View>

        <Text style={s.footer} fixed>
          Generated by Toika Export Navigator (demo)
        </Text>
      </Page>
    </Document>
  );
}
