"use client";

import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { InvoiceVars } from "@/lib/docs/invoice";
import { pdfStyles as s } from "./styles";

function Field({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ marginBottom: 6 }}>
      <Text style={s.label}>{label}</Text>
      <Text>{value || "-"}</Text>
    </View>
  );
}

/** パッキングリストPDF（インボイスとフォームを共有） */
export default function PackingListPdf({ vars }: { vars: InvoiceVars }) {
  return (
    <Document title="Packing List">
      <Page size="A4" style={s.page}>
        <Text style={s.title}>PACKING LIST</Text>

        <View style={s.row}>
          <View style={{ width: "55%", paddingRight: 12 }}>
            <Field label="Exporter / Shipper" value={`${vars.exporterName}\n${vars.exporterAddress}`} />
            <Field label="Consignee" value={`${vars.consigneeName}\n${vars.consigneeAddress}`} />
          </View>
          <View style={{ width: "45%" }}>
            <Field label="Invoice No." value={vars.invoiceNo} />
            <Field label="Date" value={vars.invoiceDate} />
            <Field label="Vessel" value={vars.vessel} />
            <Field label="Marks & Nos." value={vars.marks} />
          </View>
        </View>

        <View style={s.row}>
          <View style={{ width: "50%" }}>
            <Field label="Port of Loading" value={vars.portLoading} />
          </View>
          <View style={{ width: "50%" }}>
            <Field label="Port of Discharge" value={vars.portDischarge} />
          </View>
        </View>

        <View style={s.tableHeader}>
          <Text style={{ width: "46%" }}>Description of Goods</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>Quantity (CTNS)</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>Net Weight (kg)</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>Gross Weight (kg)</Text>
        </View>
        <View style={s.tableRow}>
          <Text style={{ width: "46%" }}>{vars.itemDesc || "-"}</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>{vars.quantity || "-"}</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>{vars.netWeight || "-"}</Text>
          <Text style={{ width: "18%", textAlign: "right" }}>{vars.grossWeight || "-"}</Text>
        </View>

        <View style={[s.signRow, { justifyContent: "flex-end" }]}>
          <View style={s.signBox}>
            <View style={s.signLine} />
            <Text style={{ fontSize: 8 }}>Signature of Exporter</Text>
          </View>
        </View>

        <Text style={s.footer} fixed>
          Generated by Toika Export Navigator (demo)
        </Text>
      </Page>
    </Document>
  );
}
